/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bbloggsbott.manual_image_selector;

public class App {

    public static void main(String[] args) {
        System.out.println("Hello");
    }
}
