/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bbloggsbott.manualimageselector;

import com.bbloggsbott.manualimageselector.presentation.MainFrame;

import javax.swing.*;
import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        String segmentedImageDir="", segmentedImageSuffix="", originalImageDir="";
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Select Original Images Directory");
        if(fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            originalImageDir = fc.getSelectedFile().getAbsolutePath();
        }

        fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setDialogTitle("Select Segmented Images Directory");
        if(fc.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
            segmentedImageDir = fc.getSelectedFile().getAbsolutePath();
        }

        segmentedImageSuffix = MainFrame.getSegmentedImageSuffix();

        new MainFrame(originalImageDir, segmentedImageDir, segmentedImageSuffix);
    }
}
